development:
  adapter: postgresql
  database: writing_dev
  host: localhost

test:
  adapter: postgresql
  database: writing_test
  host: localhost

production:
  adapter: postgresql
  database: writing
  host: localhost
